spring.application.name=employee-api

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

server.port=8080
spring.profiles.active=dev

management.endpoints.web.exposure.include=health,info
logging.level.root=INFO
logging.level.com.example.employee_api=INFO
spring.jpa.open-in-view=false